### ISSUE TITLE
Duplicate Efforts

### ISSUE THREAD

**Issue by FintanH** [nanotech/dhall-rs#5]
Hey :wave: I was just made aware that there are 2 Dhall Rust projects!

Here's a link to the other: https://github.com/Nadrieril/dhall-rust

Maybe it would be worth consolidating efforts for both projects :)

**Comment by Nadrieril** [comment]
I started my `dhall-rust` as a fork of this one because it appeared unmaintained, so there aren't actually any duplicate efforts happening unless this one comes back to life :)

**Comment by FintanH** [comment]
Ah cool! Looks like your full steam ahead anyway @Nadrieril ;)
